name: Accounts Layer CI

on:
  pull_request:
    paths:
      - "packages/base-ui/**"
      - "packages/accounts/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project: ["accounts"]
        job: ['lint', 'build', 'test:unit']
    defaults:
      run:
        working-directory: ./packages/${{ matrix.project }}
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
      with:
        version: 10
        run_install: false
    - uses: actions/setup-node@v4
      with:
        node-version: 24
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install
    - name: Set basic env
      run: |
        cp .env.example .env
    - name: ${{ matrix.job }}
      run: pnpm ${{ matrix.job }}

  e2e-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project: ["accounts"]
        shardIndex: [1, 2, 3, 4]
        shardTotal: [4]
    defaults:
      run:
        working-directory: ./packages/${{ matrix.project }}
    env:
      CI: true
      cacheid: 2
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
      with:
        version: 10
        run_install: false
    - uses: actions/setup-node@v4
      with:
        node-version: 24
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install
    - name: Cache playwright binaries
      uses: actions/cache@v4
      id: playwright-cache
      with:
        path: |
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ matrix.shardIndex }}-${{ env.cacheid }}
    - name: Install Playwright browsers
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      run: npx playwright install --with-deps
    - name: Set basic env
      run: |
        cp .env.example .env
    - name: build
      run: pnpm build
    - name: preview
      run: pnpm preview&
    - name: Run Playwright tests
      run: pnpm test:e2e --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
