name: Accounts Layer CI

on:
  pull_request:
    paths:
      - "packages/base-ui/**"
      - "packages/accounts/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project: ["accounts"]
        package: ["@dwol/accounts-layer"]
        job: ['lint', 'build', 'test:unit']
    defaults:
      run:
        working-directory: ./
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
      with:
        version: 10
        run_install: false
    - uses: actions/setup-node@v4
      with:
        node-version: 24
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm -F ${{ matrix.package }} install
    - name: Generate base layer types
      run: pnpm -F @dwol/base-layer prepare
    - name: Set basic env
      working-directory: ./packages/${{ matrix.project }}
      run: |
        cp .env.example .env
    # - name: Prepare base layer
    #   working-directory: ./packages/base-ui
    #   run: pnpm prepare accounts layer
    # - name: Prepare accounts
    #   run: pnpm prepare
    - name: ${{ matrix.job }}
      run: pnpm -F ${{ matrix.package }} ${{ matrix.job }}

  e2e-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project: ["accounts"]
        shardIndex: [1, 2]
        shardTotal: [2]
    defaults:
      run:
        working-directory: ./packages/${{ matrix.project }}
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
      with:
        version: 10
        run_install: false
    - uses: actions/setup-node@v4
      with:
        node-version: 24
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install
    - name: Install Playwright browsers
      run: npx playwright install chromium --only-shell
    - name: build
      run: pnpm build
    - name: preview
      run: pnpm preview&
    - name: Run Playwright tests
      run: pnpm test:e2e --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
