name: Base Layer CI

on:
  pull_request:
    paths:
      - "packages/base-ui/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  playwright-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2]
        shardTotal: [2]
        project: ["base-ui"]
    defaults:
      run:
        working-directory: ./packages/${{ matrix.project }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 24
    - uses: pnpm/action-setup@v4
      with:
        version: 10
        run_install: false
    - name: Install dependencies
      run: pnpm -F @dwol/base-layer install
    - name: Install dependencies
      run: pnpm -F @dwol/accounts-layer install
    - name: Install Playwright browsers
      run: npx playwright install chromium --only-shell
    - name: build
      run: pnpm build
    - name: preview
      run: pnpm preview&
    - name: Run Playwright tests
      run: pnpm test:e2e --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }} 
