name: Base Layer CI

on:
  pull_request:
    paths:
      - "packages/base-ui/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./packages/base-ui
jobs:
  base-layer-sre-ci:
    uses: bcgov/bcregistry-sre/.github/workflows/frontend-ci.yaml@main
    with:
      node_version: 24
      pnpm_version: 10
      app_name: "test"
      working_directory: ./packages/base-ui
      codecov_flag: "test"
