name: Base Layer CI

on:
  pull_request:
    paths:
      - "packages/base-ui/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  setup-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: "true"

  base-ci:
    needs: setup-job
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # project: ["base-ui"]
        package: ["@dwol/base-layer"]
        job: ['lint', 'build-check', 'test:unit']
    steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 24
    - uses: pnpm/action-setup@v4
      with:
        version: 10
        run_install: false
    - name: Install dependencies
      run: pnpm -F ${{ matrix.package }} install
    - name: ${{ matrix.job }}
      run: pnpm -F ${{ matrix.package }} ${{ matrix.job }}

  e2e-tests:
    needs: setup-job
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2]
        shardTotal: [2]
        # project: ["base-ui"]
        package: ["@dwol/base-layer"]
    steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 24
    - uses: pnpm/action-setup@v4
      with:
        version: 10
        run_install: false
    - name: Install dependencies
      run: pnpm -F ${{ matrix.package }} install
    - name: Install Playwright browsers
      run: npx playwright install chromium --only-shell
    - name: build
      run: pnpm build
    - name: preview
      run: pnpm preview&
    - name: Run Playwright tests
      run: pnpm -F ${{ matrix.package }} test:e2e --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
