jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project: ["base-ui"]
        shardIndex: [1, 2, 3, 4]
        shardTotal: [4]
    env:
      CI: true
    container:
      image: mcr.microsoft.com/playwright:v1.54.0-noble
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
      with:
        version: 10
        run_install: false
    - uses: actions/setup-node@v4
      with:
        node-version: 24
        cache: 'pnpm'

    # This runs from the repository root, which is correct.
    - name: Install dependencies
      run: pnpm install

    - name: Install Playwright browsers
      working-directory: ./packages/${{ matrix.project }}
      run: npx playwright install --with-deps

    # MODIFIED: Copy the .env.example from the package to the root .env file
    - name: Set basic env
      run: |
        cp ./packages/${{ matrix.project }}/.env.example ./.env

    - name: Run Playwright tests
      working-directory: ./packages/${{ matrix.project }}
      run: HOME=/root pnpm test:e2e --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}