jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project: ["base-ui"]
        shardIndex: [1, 2, 3, 4]
        shardTotal: [4]

    defaults:
      run:
        working-directory: ./packages/${{ matrix.project }}

    env:
      CI: true
    container:
      image: mcr.microsoft.com/playwright:v1.54.0-noble
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
      with:
        version: 10
        run_install: false
    - uses: actions/setup-node@v4
      with:
        node-version: 24
        cache: 'pnpm'

    # This will now run inside the package directory, just like your working CI
    - name: Install dependencies
      run: pnpm install

    - name: Install Playwright browsers
      run: npx playwright install --with-deps

    # MODIFIED: Copy the example file, then append the secrets to it
    - name: Set basic env with secrets
      run: |
        cp .env.example .env
        sed -i 's|NUXT_PUBLIC_ADDRESS_COMPLETE_KEY=""|NUXT_PUBLIC_ADDRESS_COMPLETE_KEY="${{ secrets.CANADA_POST_KEY }}"|g' .env

    # This will now run in the correct context
    - name: Run Playwright tests
      run: pnpm test:e2e --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}