name: 'Comment Trigger: E2E'

on:
  issue_comment:
    types: [created]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.issue.number }}
  cancel-in-progress: true

jobs:
  trigger-e2e-workflows:
    if: >-
      github.event.issue.pull_request &&
      contains(github.event.comment.body, '/e2e') &&
      (
        github.event.comment.author_association == 'MEMBER' ||
        github.event.comment.author_association == 'OWNER' ||
        github.event.comment.author_association == 'COLLABORATOR'
      )
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      actions: write

    steps:
      - name: 'Log the trigger'
        run: |
          echo "Workflow triggered by /e2e comment on PR ${{ github.event.issue.number }} by @${{ github.event.comment.user.login }}."

      - name: 'Checkout PR branch'
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.issue.number }}/merge
          fetch-depth: 0

      - name: 'Get PR base branch'
        id: get_base_branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.issue.number }}
        run: |
          echo "name=$(gh pr view $PR_NUMBER --json baseRefName -q .baseRefName)" >> $GITHUB_OUTPUT

      - name: 'Determine changed packages'
        uses: dorny/paths-filter@v3
        id: filter
        with:
          base: ${{ steps.get_base_branch.outputs.name }}
          filters: |
            base:
              - 'packages/base-ui/**'
            auth:
              - 'packages/accounts/**'
            forms:
              - 'packages/forms/**'
            pay:
              - 'packages/pay/**'

      - name: 'Trigger E2E workflows for changed packages'
        if: steps.filter.outputs.filters != '[]'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.issue.pull_request.url }}
          CHANGED_FILTERS: ${{ steps.filter.outputs.filters }}
        run: |
          echo "Changed packages: $CHANGED_FILTERS"
          
          PR_BRANCH=$(gh pr view $PR_URL --json headRefName -q .headRefName)
          echo "PR Branch: $PR_BRANCH"

          for pkg in $(echo "$CHANGED_FILTERS" | jq -r '.[]'); do
            workflow_name="e2e-${pkg}.yml"
            echo "-> Triggering workflow: $workflow_name"
            
            gh workflow run "$workflow_name" --ref "$PR_BRANCH" || echo "Warning: Workflow '$workflow_name' not found or failed to trigger."
          done

      - name: 'Add comment confirming the trigger'
        uses: actions/github-script@v7
        with:
          script: |
            const changedPackages = JSON.parse('${{ steps.filter.outputs.filters }}');
            let body;

            if (changedPackages.length > 0) {
              const packageList = changedPackages.map(p => `\`${p}\``).join(', ');
              body = `✅ E2E test workflows have been triggered for the following packages: ${packageList}.`;
            } else {
              body = `ℹ️ The /e2e command was used, but no changes were found in any packages.`;
            }
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });